### ISSUE TITLE
Complete the "Weekly incentives task tracker" board for Scoring round 6

### ISSUE THREAD

**Issue by bwhm** [Joystream/founding-members#109]
1. [ ] Add all recurring tasks
2. [ ] Convert them to issues
3. [ ] Fill in relevant data
4. [ ] Assign all issues
